name: Terraform Apply on PR merge to main

on:
  release:
    types: [edited]

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Docker image
        id: docker
        run: |
          IMAGE_TAG=front-image
          cd front_image && docker build -t $IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Debug image tag output
        run: |
          echo "Docker image tag is: ${{ steps.docker.outputs.image_tag }}"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::877680973630:role/Terraform_ECS_Backent
          aws-region: eu-central-1


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve -var="docker_image=${{ steps.docker.outputs.image_tag }}"

          #      - name: Send Telegram Notification
          #        if: success()  
          #        run: |
          #          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          #            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          #            -d text="✅ Terraform Apply Front Success " \
          #            -d parse_mode=Markdown
          #
          #
          #
      - name: Send plan to Telegram (as file)
        if: steps.Apply.outcome == 'success' 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: front-plan.txt
          message: "✅ Terraform Apply was successful for  Frontend."


      - name: Send Telegram message
        if: steps.Apply.outcome != 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ Terraform plan failed for Frontend. Please check the GitHub Actions logs."

